import { Hospital } from './types';

export const TRANSLATIONS = {
  ko: {
    findBook: "신라웰케어 120세 건강 지킴이 메디컬 및 웰니스 센터를 찾아 예약하세요",
    scheduleVisit: "가까운 메디컬 및 웰니스 센터에서 예약하세요.",
    location: "위치",
    getDirections: "카카오맵",
    patientDetails: "고객 등록",
    fullName: "성함",
    phone: "전화번호",
    email: "이메일",
    agree: "개인정보 처리에 동의합니다.",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    privacyConsent: "개인정보 수집 동의",
    bookBtn: "등록 및 예약하기",
    booked: "예약 완료!",
    confirmation: "osec0521@gmail.com으로 확인 메일이 발송되었습니다.",
    bookingNote: "등록 및 예약하기를 정상적으로 등록하신 분은 순서에 맞게 예약 담당자가 연락을 드립니다",
    chatHelp: "안녕하세요! 병원 예약이나 궁금한 점을 도와드릴까요?",
    chatPlaceholder: "메시지를 입력하세요...",
    loading: "처리중...",
    menu: "메뉴",
    alertConsent: "개인정보 처리방침에 동의해주세요.",
    chatTitle: "메디봇",
    needHelp: "등록 및 도움이 필요하신가요?",
    language: "Language",
    missingFields: "다음 정보를 입력해주세요:\n",
    inputCheck: "입력 확인",
    confirm: "확인",
    duplicatePhone: "이미 핸드폰 번호가 등록된 고객 입니다",
    duplicateEmail: "이미 이메일이 등록된 고객 입니다",
    hospitalTitle: "이용 가능 메디컬 및 웰니스 인프라",
    hospitalDesc: "프리미엄 메디컬 & 웰니스 센터"
  },
  en: {
    findBook: "Find & Book at Shill Wellcare 120-year Health Guardian Medical & Wellness Center",
    scheduleVisit: "Schedule your visit with top hospitals in your area.",
    location: "Location",
    getDirections: "Kakao Map",
    patientDetails: "Patient Details",
    fullName: "Full Name",
    phone: "Phone Number",
    email: "Email Address",
    agree: "I agree to the processing of my personal data.",
    terms: "Terms",
    privacy: "Privacy Policy",
    privacyConsent: "Privacy Policy Consent",
    bookBtn: "Book Appointment",
    booked: "Booked Successfully!",
    confirmation: "Confirmation sent to osec0521@gmail.com",
    bookingNote: "Those who have successfully registered will be contacted by the reservation manager in order.",
    chatHelp: "Hi there! I can help you find a hospital or answer questions about booking.",
    chatPlaceholder: "Ask for help...",
    loading: "Book Appointment", // Fallback if not submitting
    menu: "Menu",
    alertConsent: "Please agree to the privacy policy to continue.",
    chatTitle: "MediBot",
    needHelp: "Need help with registration?",
    language: "언어",
    missingFields: "Please enter the following fields:\n",
    inputCheck: "Check Input",
    confirm: "OK",
    duplicatePhone: "Customer with this phone number is already registered",
    duplicateEmail: "Customer with this email is already registered",
    hospitalTitle: "Available Medical & Wellness Infra",
    hospitalDesc: "Premium Medical & Wellness Centers"
  }
};

export const HOSPITALS: Hospital[] = [
  {
    id: '1',
    name: 'GV Clinic',
    nameKo: '지브이의원',
    distance: '-',
    distanceKo: '-',
    hours: '10:00 - 19:00',
    hoursKo: '10:00 - 19:00',
    subjectsKo: '포톤광양자, 인피니티웨이브, 피부성형, 문제성발톱',
    subjectsEn: 'Photon Quantum, Infinity Wave, Plastic Surgery, Problematic Toenail',
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800',
    address: '2nd Floor, 524 Nonhyeon-ro, Gangnam-gu, Seoul',
    addressKo: '대한민국 서울특별시 서초구 강남대로101길 7 루미에르 신사 2층~5층',
    regionKo: '서울',
    regionEn: 'Seoul',
    mapUrl: 'https://kko.to/ydQ40Au9vb',
    kakaoMapUrl: 'https://kko.to/ydQ40Au9vb',
    googleMapEmbedUrl: 'https://maps.app.goo.gl/jTMQ9HkeZzWJx8Fx5'
  },
  {
    id: '2',
    name: 'Shesheal Clinic',
    nameKo: '쉬즈힐의원',
    distance: '-',
    distanceKo: '-',
    hours: '09:00 - 19:00',
    hoursKo: '09:00 - 19:00',
    subjectsKo: '제노시스항노화면역센터, 여성/남성 성기능 강화',
    subjectsEn: 'Cancer Patient Treatment, Male/Female Sexual Function Enhancement',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    address: '3rd Floor, 613 Eonju-ro, Gangnam-gu, Seoul',
    addressKo: '서울특별시 서초구 강남대로 623 우일빌딩 지하 1층 1층, 2층, 7층',
    regionKo: '서울',
    regionEn: 'Seoul',
    mapUrl: 'https://kko.to/s5dLedD_cy',
    kakaoMapUrl: 'https://kko.to/s5dLedD_cy',
    googleMapEmbedUrl: 'https://maps.app.goo.gl/y3LQLsdJFW6R6goe6'
  },
  {
    id: '3',
    name: 'Cellpia Clinic',
    nameKo: '셀피아의원',
    distance: '-',
    distanceKo: '-',
    hours: '09:00 - 19:00',
    hoursKo: '09:00 - 19:00',
    subjectsKo: '줄기세포 전문',
    subjectsEn: 'Stem Cell Specialist',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=800',
    address: '2nd Floor, 419 Eonju-ro, Gangnam-gu, Seoul',
    addressKo: '서울 강남구 언주로 419 2층',
    regionKo: '서울',
    regionEn: 'Seoul',
    mapUrl: 'https://kko.to/TkD010skjL',
    kakaoMapUrl: 'https://kko.to/TkD010skjL',
    googleMapEmbedUrl: 'https://maps.app.goo.gl/uXvdjdmYyvQQTPwb9'
  },
  {
    id: '4',
    name: 'Chaeum Oriental Hospital',
    nameKo: '채움한방병원',
    distance: '-',
    distanceKo: '-',
    hours: '09:00 - 19:00',
    hoursKo: '09:00 - 19:00',
    subjectsKo: '포톤광양자',
    subjectsEn: 'Photon Quantum',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    address: '10th Floor, 419 Eonju-ro, Gangnam-gu, Seoul',
    addressKo: '경기도 성남시 중원구 둔촌대로80번길 3-10 아리스타 3층',
    regionKo: '경기',
    regionEn: 'Gyeonggi',
    mapUrl: 'https://kko.to/ULdoPvGVUl',
    kakaoMapUrl: 'https://kko.to/ULdoPvGVUl',
    googleMapEmbedUrl: 'https://maps.app.goo.gl/xnm4WYYHX1fgmDRF6'
  },
  {
    id: '5',
    name: 'Daejeon (April)',
    nameKo: '대전 (4월중 예정)',
    distance: '-',
    distanceKo: '-',
    hours: 'Coming Soon',
    hoursKo: '오픈 예정',
    subjectsKo: '포톤광양자',
    subjectsEn: 'Photon Quantum',
    rating: 0,
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    address: 'Daejeon, South Korea',
    addressKo: '대전광역시',
    regionKo: '대전',
    regionEn: 'Daejeon'
  },
  {
    id: '6',
    name: 'Busan (May)',
    nameKo: '부산 (5월중 예정)',
    distance: '-',
    distanceKo: '-',
    hours: 'Coming Soon',
    hoursKo: '오픈 예정',
    subjectsKo: '포톤광양자',
    subjectsEn: 'Photon Quantum',
    rating: 0,
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    address: 'Busan, South Korea',
    addressKo: '부산광역시',
    regionKo: '부산',
    regionEn: 'Busan'
  },
  {
    id: '7',
    name: 'Jeju (2nd Half)',
    nameKo: '제주도 (하반기 예정)',
    distance: '-',
    distanceKo: '-',
    hours: 'Coming Soon',
    hoursKo: '오픈 예정',
    subjectsKo: '포톤광양자',
    subjectsEn: 'Photon Quantum',
    rating: 0,
    image: 'https://images.unsplash.com/photo-1504814532849-cff240bbc503?auto=format&fit=crop&q=80&w=800',
    address: 'Jeju, South Korea',
    addressKo: '제주특별자치도',
    regionKo: '제주도',
    regionEn: 'Jeju'
  },
  {
    id: '8',
    name: 'Vietnam Hanoi (1st Half)',
    nameKo: '베트남 하노이 (상반기 예정)',
    distance: '-',
    distanceKo: '-',
    hours: 'Coming Soon',
    hoursKo: '오픈 예정',
    rating: 0,
    image: 'https://images.unsplash.com/photo-1506701908217-2a2b24f4021a?auto=format&fit=crop&q=80&w=800',
    address: 'Hanoi, Vietnam',
    addressKo: '베트남 하노이',
    regionKo: '베트남',
    regionEn: 'Vietnam'
  }
];

export const GOOGLE_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbx_YOUR_SCRIPT_ID_HERE/exec';